NUM_ITEM_OUTPUTS = 4
NUM_ENEMY_OUTPUTS = 4
OUTPUT_MENHIR = 4
OUTPUT_EXPLORE = 5
OUTPUT_ENEMY_BASE = 6
OUTPUT_ESCAPE_BASE = 10
NUM_NN_OUTPUTS = OUTPUT_ESCAPE_BASE + NUM_ENEMY_OUTPUTS

MASK_DISABLED = -1e18
